### ISSUE TITLE
Update Eligibility section

### ISSUE THREAD

**Issue by CBID2** [Rishabh04-02/The-Beginners-Guide-to-Google-Summer-of-Code-GSoC#12]
Hi @Rishabh04-02! I just read GSOC's [latest blog post](https://opensource.googleblog.com/2022/11/get-ready-for-google-summer-of-code-2023.html). They mention that starting next year, non-students who are also beginners in Open Source can apply, so I highly recommend adding this information to the Eligibility section in your guide (if granted permission, I can add this information myself via PR).

**Comment by Rishabh04-02** [comment]
@CBID2 Thanks for the information.

Sure, go ahead and add the information.
also, don't forget to include the above link in that.

**Comment by CBID2** [comment]
Hi @Rishabh04-02! :) I made the PR: https://github.com/Rishabh04-02/The-Beginners-Guide-to-Google-Summer-of-Code-GSoC/pull/13
